version: '2'
services:
  backend:
    container_name: react_backend
    build: ./app-react-crud-backend
    # command: npm run dev
    ports: 
      - "9999:8081"
    volumes:
      - ./app-react-crud-backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  frontend:
    container_name: react_frontend
    build: ./app-react-crud-frontend
    ports:
      - "8080:3000"
    volumes:
      - ./app-react-crud-frontend:/usr/src/app
      - /usr/src/app/node_modules
  